parameters:
  - name: environment
    type: string
    default: 'prod'
    values:
      - prod
      - local
      - AB123

variables:
  ENABLESIMPLESAMLPHPSSO: 'true' # Set to 'true' to enable SimpleSAMLphp SSO deployment
  dockerRegistryServiceConnection: 'ilifes-acr-docker'
  dockerRepository: 'simplesamlphp'

stages:
  - stage: Build
    condition: eq(variables['ENABLESIMPLESAMLPHPSSO'], 'true')
    displayName: 'Build Stage'
    jobs:
      - job: BuildJob
        pool:
          name: 'Default'

        displayName: 'Build SimpleSAMLphp'
        steps:
          - script: |
              echo "Listing files after checkout:"
              ls -laR $(Pipeline.Workspace)
            displayName: 'Debug: List Workspace Files'

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)

          - task: Docker@2
            displayName: 'Build SimpleSAMLphp Image'
            inputs:
              command: build
              containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
              repository: simplesamlphp
              Dockerfile: $(Build.SourcesDirectory)/bp-simplesamlphp/Dockerfile
              buildContext: $(Build.SourcesDirectory)/bp-simplesamlphp
              tags: latest


          - task: Docker@2
            displayName: 'Push SimpleSAMLphp Image'
            condition: eq(variables['ENABLESIMPLESAMLPHPSSO'], 'true')
            inputs:
              command: push
              containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
              repository: simplesamlphp
              tags: latest

  - stage: Deploy
    displayName: 'Deploy Stage'
    dependsOn: Build
    condition: eq(variables['ENABLESIMPLESAMLPHPSSO'], 'true')
    jobs:
      - job: DeployJob
        displayName: "Deploy to ACR"
        pool:
          name: 'Default'

        steps:
          - script: |
              echo "Listing files after checkout:"
              ls -laR $(Pipeline.Workspace)
            displayName: 'Debug: List Workspace Files'

          - task: Docker@2
            displayName: 'Login to ACR'
            inputs:
              command: login
              containerRegistry: $(dockerRegistryServiceConnection)

          - task: Docker@2
            displayName: 'Pull SimpleSAMLphp Image'
            condition: eq(variables['ENABLESIMPLESAMLPHPSSO'], 'true')
            inputs:
              command: pull
              containerRegistry: ${{ parameters.dockerRegistryServiceConnection }}
              repository: simplesamlphp
              tags: latest

          - script: |
              echo "Deploying SimpleSAMLphp to environment: ${{ parameters.environment }}"
            displayName: 'Deploy SimpleSAMLphp'
          # Make dockers containers down before running new ones
          - script: |
              docker-compose -f $(Build.SourcesDirectory)/bp-simplesamlphp/docker-compose.yml down
            displayName: 'Stop Existing Containers' 
          # Run new containers with the latest image
          - script: |
              docker-compose -f $(Build.SourcesDirectory)/bp-simplesamlphp/docker-compose.yml up -d
            displayName: 'Start New Containers'

          - script: |
              echo "SimpleSAMLphp deployed successfully to environment: ${{ parameters.environment }}"
            displayName: 'Deployment Success Message'