version: "3.8"

services:
  simplesamlphp:
    image: ghcr.io/buildprocure/bp-simplesamlphp:latest
    container_name: simplesamlphp
    restart: unless-stopped
    env_file:
      - php-env-prod.env
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    external: true
