version: "3.8"

services:
  simplesaml:
    image: ilifesregistry.azurecr.io/simplesamlphp:latest
    container_name: simplesamlphp
    ports:
      - "8081:80"
    restart: unless-stopped
    networks:
      - app-network
